name = "government-portal"
main = "worker/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

keep_vars = true

# ============================================================
# Environment Variables
# ============================================================
[vars]
AUTH_SECRET = "a7f3c9e2b8d4f1a6c5e9b2d7f4a8c3e6b2f5a8c1e4b7d0f3a6c9e2b5d8f1a4"
IMAGEKIT_PRIVATE_KEY = "private_W4heGM/F61JWhrHs3gJ6HNlcU="
IMAGEKIT_PUBLIC_KEY = "public_Uz2lL64W7ii800m9cRu9p+8w0="
IMAGEKIT_URL_ENDPOINT = "https://ik.imagekit.io/m15kd0rkyd"
SITE_URL = "https://government-portal.-233.workers.dev"

# ============================================================
# D1 Database
# ============================================================
[[d1_databases]]
binding = "DB"
database_name = "gov-portal-db"
database_id = "e937a542-4d91-4c00-884a-6d0f4afc4131"

# ============================================================
# Static Assets (React build)
# ============================================================
[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
