-- ⚠️ DEMO / SAMPLE DATA — for development only.
-- These are fictional entries for UI testing. Not real government notifications.

INSERT INTO posts
(title, slug, category_id, short_description, content, organization, post_name, total_vacancy,
 application_start_date, application_last_date, exam_date, salary, age_limit, application_fee,
 eligibility, selection_process, how_to_apply, important_dates, important_links,
 official_website, status, seo_title, seo_description)
VALUES
-- JOBS (cat 1)
('Demo State Services Recruitment 2026','demo-state-services-recruitment-2026',1,
 'Sample recruitment for demonstration purposes.',
 '<p>This is a demo post. Replace with real content.</p>',
 'Demo Public Service Commission','Combined Services','250',
 '2026-01-10','2026-02-15','2026-04-20','₹56,100 – ₹1,77,500','21–32 years','₹400',
 'Bachelor''s degree in any discipline from a recognised university.',
 'Preliminary Exam → Main Exam → Interview',
 'Apply online via the official portal.',
 'Start: 10 Jan 2026 | Last: 15 Feb 2026',
 'Apply Online|https://example.com/apply',
 'https://example.com','published',
 'Demo State Services Recruitment 2026 — Notification',
 'Sample government recruitment notification for demo purposes.'),

('Demo Bank Clerk Recruitment 2026','demo-bank-clerk-recruitment-2026',1,
 'Sample bank clerk recruitment notice.','<p>Demo content.</p>',
 'Demo National Bank','Clerk','1200','2026-02-01','2026-03-01','2026-05-10',
 '₹28,000 – ₹35,000','20–28 years','₹600',
 'Graduation in any stream.','Written Test → Interview',
 'Apply online.','Start: 1 Feb 2026 | Last: 1 Mar 2026',NULL,
 'https://example.com','published','Demo Bank Clerk Recruitment 2026','Sample bank recruitment post.'),

('Demo Railway Group D Recruitment 2026','demo-railway-group-d-recruitment-2026',1,
 'Sample railway recruitment.','<p>Demo content.</p>','Demo Railways','Group D','5000',
 '2026-01-20','2026-03-05','2026-06-15','₹18,000 – ₹22,000','18–33 years','₹500',
 '10th pass or ITI equivalent.','CBT → PET → DV','Apply online.',NULL,NULL,
 'https://example.com','published','Demo Railway Group D 2026','Sample railway recruitment.'),

('Demo Police Constable Recruitment 2026','demo-police-constable-recruitment-2026',1,
 'Sample police recruitment.','<p>Demo content.</p>','Demo State Police','Constable','8000',
 '2026-02-10','2026-03-20','2026-05-25','₹21,700 – ₹69,100','18–25 years','₹500',
 '12th pass.','Written → Physical → Medical','Apply online.',NULL,NULL,
 'https://example.com','published','Demo Police Constable Recruitment 2026','Sample police recruitment.'),

('Demo Teacher Recruitment 2026','demo-teacher-recruitment-2026',1,
 'Sample teacher recruitment.','<p>Demo content.</p>','Demo Education Board','Primary Teacher','3200',
 '2026-03-01','2026-04-01','2026-06-01','₹35,400 – ₹1,12,400','21–40 years','₹700',
 'B.Ed with graduation.','Written → Interview','Apply online.',NULL,NULL,
 'https://example.com','published','Demo Teacher Recruitment 2026','Sample teacher recruitment.'),

('Demo PSU Engineer Recruitment 2026','demo-psu-engineer-recruitment-2026',1,
 'Sample PSU engineer recruitment.','<p>Demo content.</p>','Demo PSU','Engineer Trainee','600',
 '2026-01-25','2026-03-10','2026-05-15','₹50,000 – ₹1,60,000','21–30 years','₹800',
 'B.E/B.Tech in relevant branch.','GATE Score → Interview','Apply online.',NULL,NULL,
 'https://example.com','published','Demo PSU Engineer Recruitment 2026','Sample PSU recruitment.'),

('Demo Defence NDA Recruitment 2026','demo-defence-nda-recruitment-2026',1,
 'Sample NDA recruitment.','<p>Demo content.</p>','Demo Defence','NDA Cadet','450',
 '2026-01-05','2026-02-05','2026-04-18','₹56,100+','16.5–19.5 years','₹100',
 '12th pass (PCM for Navy/Air Force).','Written → SSB → Medical','Apply online.',NULL,NULL,
 'https://example.com','published','Demo NDA Recruitment 2026','Sample defence recruitment.'),

('Demo Court Clerk Recruitment 2026','demo-court-clerk-recruitment-2026',1,
 'Sample court clerk recruitment.','<p>Demo content.</p>','Demo High Court','Clerk','1500',
 '2026-02-15','2026-03-25','2026-05-30','₹19,900 – ₹63,200','18–40 years','₹500',
 'Graduation with typing skill.','Written → Skill Test','Apply online.',NULL,NULL,
 'https://example.com','published','Demo Court Clerk Recruitment 2026','Sample court recruitment.'),

('Demo Post Office Recruitment 2026','demo-post-office-recruitment-2026',1,
 'Sample post office recruitment.','<p>Demo content.</p>','Demo Postal Circle','GDS','2200',
 '2026-03-05','2026-04-05','2026-06-10','₹12,000 – ₹29,380','18–40 years','₹100',
 '10th pass.','Merit-based','Apply online.',NULL,NULL,
 'https://example.com','published','Demo Post Office Recruitment 2026','Sample postal recruitment.'),

('Demo University Non-Teaching Recruitment 2026','demo-univ-nonteaching-2026',1,
 'Sample university recruitment.','<p>Demo content.</p>','Demo University','Non-Teaching Staff','300',
 '2026-02-20','2026-03-30','2026-05-20','₹25,500 – ₹81,100','18–35 years','₹600',
 'Graduation.','Written → Interview','Apply online.',NULL,NULL,
 'https://example.com','published','Demo University Non-Teaching Recruitment 2026','Sample university recruitment.'),

-- RESULTS (cat 2)
('Demo Board Class 10 Result 2026','demo-board-class10-result-2026',2,
 'Sample class 10 result.','<p>Demo.</p>','Demo Board',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,NULL,'https://example.com','published','Demo Board Class 10 Result 2026','Sample result.'),

('Demo Board Class 12 Result 2026','demo-board-class12-result-2026',2,
 'Sample class 12 result.','<p>Demo.</p>','Demo Board',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,NULL,'https://example.com','published','Demo Board Class 12 Result 2026','Sample result.'),

('Demo SSC Result 2026','demo-ssc-result-2026',2,'Sample SSC result.','<p>Demo.</p>',
 'Demo SSC',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo SSC Result 2026','Sample SSC result.'),

('Demo UPSC Prelims Result 2026','demo-upsc-prelims-result-2026',2,'Sample UPSC result.','<p>Demo.</p>',
 'Demo UPSC',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo UPSC Prelims Result 2026','Sample UPSC result.'),

('Demo Banking Result 2026','demo-banking-result-2026',2,'Sample banking result.','<p>Demo.</p>',
 'Demo Bank',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo Banking Result 2026','Sample banking result.'),

('Demo NEET UG Result 2026','demo-neet-ug-result-2026',2,'Sample NEET result.','<p>Demo.</p>',
 'Demo NTA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo NEET UG Result 2026','Sample NEET result.'),

('Demo JEE Main Result 2026','demo-jee-main-result-2026',2,'Sample JEE result.','<p>Demo.</p>',
 'Demo NTA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo JEE Main Result 2026','Sample JEE result.'),

('Demo Police Result 2026','demo-police-result-2026',2,'Sample police result.','<p>Demo.</p>',
 'Demo Police',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo Police Result 2026','Sample police result.'),

-- ADMIT CARDS (cat 3)
('Demo SSC Admit Card 2026','demo-ssc-admit-card-2026',3,'Sample SSC admit card.','<p>Demo.</p>',
 'Demo SSC',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo SSC Admit Card 2026','Sample SSC admit card.'),
('Demo Railway Admit Card 2026','demo-railway-admit-card-2026',3,'Sample railway admit card.','<p>Demo.</p>',
 'Demo Railways',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo Railway Admit Card 2026','Sample railway admit card.'),
('Demo Bank Admit Card 2026','demo-bank-admit-card-2026',3,'Sample bank admit card.','<p>Demo.</p>',
 'Demo Bank',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo Bank Admit Card 2026','Sample bank admit card.'),
('Demo Police Admit Card 2026','demo-police-admit-card-2026',3,'Sample police admit card.','<p>Demo.</p>',
 'Demo Police',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo Police Admit Card 2026','Sample police admit card.'),
('Demo UPSC Admit Card 2026','demo-upsc-admit-card-2026',3,'Sample UPSC admit card.','<p>Demo.</p>',
 'Demo UPSC',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo UPSC Admit Card 2026','Sample UPSC admit card.'),
('Demo NEET Admit Card 2026','demo-neet-admit-card-2026',3,'Sample NEET admit card.','<p>Demo.</p>',
 'Demo NTA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo NEET Admit Card 2026','Sample NEET admit card.'),
('Demo JEE Admit Card 2026','demo-jee-admit-card-2026',3,'Sample JEE admit card.','<p>Demo.</p>',
 'Demo NTA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo JEE Admit Card 2026','Sample JEE admit card.'),
('Demo University Admit Card 2026','demo-univ-admit-card-2026',3,'Sample university admit card.','<p>Demo.</p>',
 'Demo University',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo University Admit Card 2026','Sample university admit card.'),

-- ADMISSION (cat 4)
('Demo Engineering Admission 2026','demo-engineering-admission-2026',4,'Sample engineering admission.','<p>Demo.</p>',
 'Demo Institute',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo Engineering Admission 2026','Sample admission.'),
('Demo Medical Admission 2026','demo-medical-admission-2026',4,'Sample medical admission.','<p>Demo.</p>',
 'Demo Institute',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo Medical Admission 2026','Sample admission.'),
('Demo Law Admission 2026','demo-law-admission-2026',4,'Sample law admission.','<p>Demo.</p>',
 'Demo Institute',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo Law Admission 2026','Sample admission.'),
('Demo MBA Admission 2026','demo-mba-admission-2026',4,'Sample MBA admission.','<p>Demo.</p>',
 'Demo Institute',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo MBA Admission 2026','Sample admission.'),
('Demo Agriculture Admission 2026','demo-agri-admission-2026',4,'Sample agriculture admission.','<p>Demo.</p>',
 'Demo Institute',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo Agriculture Admission 2026','Sample admission.'),

-- SCHOLARSHIP (cat 5)
('Demo Merit Scholarship 2026','demo-merit-scholarship-2026',5,'Sample merit scholarship.','<p>Demo.</p>',
 'Demo Foundation',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo Merit Scholarship 2026','Sample scholarship.'),
('Demo SC ST Scholarship 2026','demo-sc-st-scholarship-2026',5,'Sample SC/ST scholarship.','<p>Demo.</p>',
 'Demo Foundation',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo SC ST Scholarship 2026','Sample scholarship.'),
('Demo Minority Scholarship 2026','demo-minority-scholarship-2026',5,'Sample minority scholarship.','<p>Demo.</p>',
 'Demo Foundation',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo Minority Scholarship 2026','Sample scholarship.'),
('Demo Girl Child Scholarship 2026','demo-girl-child-scholarship-2026',5,'Sample girl child scholarship.','<p>Demo.</p>',
 'Demo Foundation',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo Girl Child Scholarship 2026','Sample scholarship.'),
('Demo Sports Scholarship 2026','demo-sports-scholarship-2026',5,'Sample sports scholarship.','<p>Demo.</p>',
 'Demo Foundation',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo Sports Scholarship 2026','Sample scholarship.'),

-- SCHEMES (cat 6)
('Demo Farmer Welfare Scheme 2026','demo-farmer-welfare-scheme-2026',6,'Sample scheme.','<p>Demo.</p>',
 'Demo Ministry',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo Farmer Welfare Scheme 2026','Sample scheme.'),
('Demo Housing Scheme 2026','demo-housing-scheme-2026',6,'Sample scheme.','<p>Demo.</p>',
 'Demo Ministry',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo Housing Scheme 2026','Sample scheme.'),
('Demo Health Insurance Scheme 2026','demo-health-insurance-scheme-2026',6,'Sample scheme.','<p>Demo.</p>',
 'Demo Ministry',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo Health Insurance Scheme 2026','Sample scheme.'),
('Demo Women Empowerment Scheme 2026','demo-women-empowerment-scheme-2026',6,'Sample scheme.','<p>Demo.</p>',
 'Demo Ministry',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo Women Empowerment Scheme 2026','Sample scheme.'),
('Demo Skill Development Scheme 2026','demo-skill-development-scheme-2026',6,'Sample scheme.','<p>Demo.</p>',
 'Demo Ministry',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo Skill Development Scheme 2026','Sample scheme.'),

-- NEWS (cat 7)
('Demo Education Policy Update 2026','demo-education-policy-update-2026',7,'Sample news.','<p>Demo.</p>',
 'Demo Newsroom',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo Education Policy Update 2026','Sample news.'),
('Demo Exam Schedule Announced','demo-exam-schedule-announced',7,'Sample news.','<p>Demo.</p>',
 'Demo Newsroom',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo Exam Schedule Announced','Sample news.'),
('Demo New Recruitment Board','demo-new-recruitment-board',7,'Sample news.','<p>Demo.</p>',
 'Demo Newsroom',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo New Recruitment Board','Sample news.'),
('Demo Scholarship Deadline Extended','demo-scholarship-deadline-extended',7,'Sample news.','<p>Demo.</p>',
 'Demo Newsroom',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo Scholarship Deadline Extended','Sample news.'),
('Demo Digital India Update','demo-digital-india-update',7,'Sample news.','<p>Demo.</p>',
 'Demo Newsroom',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo Digital India Update','Sample news.'),
('Demo Job Fair 2026','demo-job-fair-2026',7,'Sample news.','<p>Demo.</p>',
 'Demo Newsroom',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo Job Fair 2026','Sample news.'),
('Demo New Skill Program Launched','demo-new-skill-program-launched',7,'Sample news.','<p>Demo.</p>',
 'Demo Newsroom',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo New Skill Program Launched','Sample news.'),
('Demo Higher Education Reform','demo-higher-education-reform',7,'Sample news.','<p>Demo.</p>',
 'Demo Newsroom',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'https://example.com','published','Demo Higher Education Reform','Sample news.');
